import type { Tour } from "./types";

export const MOCK_TOURS: Tour[] = [
  {
    id: "11111111-1111-4111-8111-111111111101",
    slug: "great-barrier-reef-snorkel",
    title: "Great Barrier Reef Snorkel Day Trip",
    operator_name: "Reef Explorer Cairns",
    operator_location: "Cairns, QLD",
    description:
      "Full-day outer reef pontoon with snorkelling gear, buffet lunch and marine biologist briefing.",
    long_description:
      "Join Reef Explorer Cairns for a full day on the outer Great Barrier Reef. Depart Cairns marina at 8:30am aboard a fast catamaran. Spend 4 hours at a private pontoon with snorkelling platforms, glass-bottom boat tours and an optional scuba intro dive. A marine biologist walks you through the reef ecosystem before you hit the water. Buffet lunch, morning tea and all snorkelling equipment included.",
    destination: "Great Barrier Reef",
    state: "Queensland",
    duration: "8 hours",
    price_aud: 189,
    commission_rate: 0.15,
    max_guests: 40,
    image_url:
      "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?auto=format&fit=crop&w=1200&q=80",
    highlights: ["Outer reef pontoon", "Marine biologist talk", "Buffet lunch included"],
    includes: ["Snorkel gear", "Return transfers", "Reef levy", "Morning tea"],
    meeting_point: "Reef Fleet Terminal, 1 Spence St, Cairns",
    rating: 4.9,
    review_count: 312,
    featured: true,
  },
  {
    id: "11111111-1111-4111-8111-111111111102",
    slug: "blue-mountains-day-trip",
    title: "Blue Mountains & Three Sisters Day Trip",
    operator_name: "Blue Mountains Adventures",
    operator_location: "Katoomba, NSW",
    description:
      "Scenic rail, rainforest walks and Three Sisters lookout with a small-group guide from Sydney.",
    long_description:
      "Escape Sydney for a small-group day in the Blue Mountains. Travel by comfortable minibus to Katoomba, ride the Scenic Railway, walk the Cliff Walk to Three Sisters lookout, and visit Wentworth Falls. Your local guide shares Darug Country stories and hidden photo spots tourists miss. Morning tea and national park entry included.",
    destination: "Blue Mountains",
    state: "New South Wales",
    duration: "10 hours",
    price_aud: 129,
    commission_rate: 0.15,
    max_guests: 14,
    image_url:
      "https://images.unsplash.com/photo-1506973035872-a4ec16b8ebb8?auto=format&fit=crop&w=1200&q=80",
    highlights: ["Scenic Railway", "Three Sisters", "Small group (max 14)"],
    includes: ["Sydney pickup", "National park fees", "Morning tea", "Local guide"],
    meeting_point: "Circular Quay, Wharf 5, Sydney",
    rating: 4.8,
    review_count: 198,
    featured: true,
  },
  {
    id: "11111111-1111-4111-8111-111111111103",
    slug: "uluru-sunset-field-of-light",
    title: "Uluru Sunset & Field of Light",
    operator_name: "Red Centre Experiences",
    operator_location: "Yulara, NT",
    description:
      "Sunset canapés at Uluru followed by the Field of Light art installation after dark.",
    long_description:
      "Watch Uluru glow at sunset from a private dune viewing area with sparkling wine and canapés. As darkness falls, wander through Bruce Munro's Field of Light — 50,000 solar-powered stems spreading across the desert. An Anangu guide shares creation stories. Return transfers from Ayers Rock Resort included.",
    destination: "Uluru",
    state: "Northern Territory",
    duration: "4 hours",
    price_aud: 245,
    commission_rate: 0.15,
    max_guests: 24,
    image_url:
      "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=1200&q=80",
    highlights: ["Sunset viewing", "Field of Light entry", "Anangu guide"],
    includes: ["Resort transfers", "Canapés", "Sparkling wine", "Park pass"],
    meeting_point: "Ayers Rock Resort Town Square",
    rating: 4.9,
    review_count: 156,
    featured: true,
  },
  {
    id: "11111111-1111-4111-8111-111111111104",
    slug: "phillip-island-penguins",
    title: "Phillip Island Penguin Parade",
    operator_name: "Penguin Tours Victoria",
    operator_location: "Phillip Island, VIC",
    description:
      "Afternoon coastal drive, koala boardwalk and premium penguin viewing at sunset.",
    long_description:
      "Leave Melbourne mid-afternoon for Phillip Island. Stop at the Koala Conservation Reserve boardwalk, stroll Cape Woolamai beach, then take premium seats at the Penguin Parade as little penguins waddle ashore at dusk. Small bus, max 20 guests. Dinner stop in San Remo on the return drive.",
    destination: "Phillip Island",
    state: "Victoria",
    duration: "9 hours",
    price_aud: 95,
    commission_rate: 0.15,
    max_guests: 20,
    image_url:
      "https://images.unsplash.com/photo-1558642452-9d2a7aff7a2b?auto=format&fit=crop&w=1200&q=80",
    highlights: ["Premium penguin seats", "Koala boardwalk", "Cape Woolamai"],
    includes: ["Melbourne pickup", "Penguin Parade ticket", "National park fees"],
    meeting_point: "Federation Square, Melbourne",
    rating: 4.7,
    review_count: 421,
    featured: false,
  },
  {
    id: "11111111-1111-4111-8111-111111111105",
    slug: "freycinet-oyster-kayak",
    title: "Freycinet Oyster Farm Kayak",
    operator_name: "Tassie Coastal Co",
    operator_location: "Coles Bay, TAS",
    description:
      "Paddle crystal waters, shuck fresh oysters on the water and walk to Wineglass Bay lookout.",
    long_description:
      "Start with a guided kayak across sheltered Coles Bay to a floating oyster farm. Shuck and taste Pacific oysters straight from the lease. After lunch, a short guided walk to Wineglass Bay lookout for one of Tasmania's most photographed views. All kayaking gear and wetsuits provided.",
    destination: "Freycinet",
    state: "Tasmania",
    duration: "6 hours",
    price_aud: 165,
    commission_rate: 0.15,
    max_guests: 10,
    image_url:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80",
    highlights: ["Oyster farm visit", "Kayaking", "Wineglass Bay lookout"],
    includes: ["Kayak & wetsuit", "Oyster tasting", "Park pass", "Local guide"],
    meeting_point: "Freycinet National Park Visitor Centre",
    rating: 4.9,
    review_count: 87,
    featured: true,
  },
  {
    id: "11111111-1111-4111-8111-111111111106",
    slug: "rottnest-island-bike-snorkel",
    title: "Rottnest Island Bike & Snorkel",
    operator_name: "Island Hopper WA",
    operator_location: "Fremantle, WA",
    description:
      "Ferry to Rottnest, bike hire, snorkel at The Basin and a selfie stop with quokkas.",
    long_description:
      "Catch the fast ferry from Fremantle to Rottnest Island. Collect your bike at the pier and follow a mapped coastal loop to The Basin for snorkelling in turquoise water. Pause at Parker Point for quokka spotting (no touching!). Return ferry late afternoon. Snorkel gear and bike hire included.",
    destination: "Rottnest Island",
    state: "Western Australia",
    duration: "7 hours",
    price_aud: 112,
    commission_rate: 0.15,
    max_guests: 30,
    image_url:
      "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=1200&q=80",
    highlights: ["Bike hire", "The Basin snorkel", "Quokka spotting"],
    includes: ["Return ferry", "Bike hire", "Snorkel set", "Island map"],
    meeting_point: "B-Shed Ferry Terminal, Fremantle",
    rating: 4.8,
    review_count: 264,
    featured: false,
  },
  {
    id: "11111111-1111-4111-8111-111111111107",
    slug: "daintree-rainforest-walk",
    title: "Daintree Rainforest & Mossman Gorge",
    operator_name: "Daintree Cultural Walks",
    operator_location: "Port Douglas, QLD",
    description:
      "Kuku Yalanji-led walk through Mossman Gorge and a Daintree river crocodile cruise.",
    long_description:
      "Travel north from Port Douglas with a Kuku Yalanji guide. Walk the Mossman Gorge circuit learning bush tucker and traditional uses of native plants. After lunch, cruise the Daintree River spotting estuarine crocodiles and kingfishers. Small group, max 12. A genuine Indigenous-led experience.",
    destination: "Daintree",
    state: "Queensland",
    duration: "8 hours",
    price_aud: 98,
    commission_rate: 0.15,
    max_guests: 12,
    image_url:
      "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1200&q=80",
    highlights: ["Indigenous guide", "Mossman Gorge", "River cruise"],
    includes: ["Guide fees", "River cruise", "Lunch", "Port Douglas pickup"],
    meeting_point: "Port Douglas Marina Mirage",
    rating: 4.9,
    review_count: 143,
    featured: false,
  },
  {
    id: "11111111-1111-4111-8111-111111111108",
    slug: "barossa-valley-wine-tour",
    title: "Barossa Valley Small-Batch Wine Tour",
    operator_name: "Barossa Small Batch",
    operator_location: "Tanunda, SA",
    description:
      "Visit three family-owned cellar doors with cheese platters and a winemaker meet-and-greet.",
    long_description:
      "Skip the big commercial wineries. This tour visits three family-run Barossa cellar doors — including a Grenache specialist and a biodynamic vineyard. Meet a winemaker over a shared platter of local cheese and charcuterie. Depart Adelaide 9am, return by 5pm. Max 8 guests per bus.",
    destination: "Barossa Valley",
    state: "South Australia",
    duration: "8 hours",
    price_aud: 175,
    commission_rate: 0.15,
    max_guests: 8,
    image_url:
      "https://images.unsplash.com/photo-1506377247377-2ccd5b3d8ffe?auto=format&fit=crop&w=1200&q=80",
    highlights: ["Family wineries", "Winemaker meet", "Cheese platters"],
    includes: ["Tastings at 3 wineries", "Cheese platter", "Adelaide transfers"],
    meeting_point: "Adelaide Central Market, Gouger St",
    rating: 4.8,
    review_count: 176,
    featured: false,
  },
];
