import { defineField, defineType } from "sanity";

export const homepage = defineType({
  name: "homepage",
  title: "Homepage",
  type: "document",
  groups: [
    { name: "hero", title: "Hero", default: true },
    { name: "featured", title: "Featured tours" },
    { name: "howItWorks", title: "How it works" },
    { name: "operators", title: "For operators" },
    { name: "cta", title: "Bottom CTA" },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Eyebrow",
      type: "string",
      group: "hero",
    }),
    defineField({
      name: "heroTitle",
      title: "Headline (before highlight)",
      type: "string",
      group: "hero",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "heroTitleHighlight",
      title: "Headline highlight",
      type: "string",
      group: "hero",
    }),
    defineField({
      name: "heroSubtitle",
      title: "Subtitle",
      type: "text",
      rows: 4,
      group: "hero",
    }),
    defineField({
      name: "heroPrimaryCtaLabel",
      title: "Primary button label",
      type: "string",
      group: "hero",
    }),
    defineField({
      name: "heroPrimaryCtaHref",
      title: "Primary button link",
      type: "string",
      group: "hero",
    }),
    defineField({
      name: "heroSecondaryCtaLabel",
      title: "Secondary button label",
      type: "string",
      group: "hero",
    }),
    defineField({
      name: "heroSecondaryCtaHref",
      title: "Secondary button link",
      type: "string",
      group: "hero",
    }),
    defineField({
      name: "heroBadges",
      title: "Trust badges",
      type: "array",
      of: [{ type: "string" }],
      group: "hero",
    }),
    defineField({
      name: "featuredEyebrow",
      title: "Eyebrow",
      type: "string",
      group: "featured",
    }),
    defineField({
      name: "featuredTitle",
      title: "Title",
      type: "string",
      group: "featured",
    }),
    defineField({
      name: "featuredDescription",
      title: "Description",
      type: "text",
      rows: 3,
      group: "featured",
    }),
    defineField({
      name: "howItWorksEyebrow",
      title: "Eyebrow",
      type: "string",
      group: "howItWorks",
    }),
    defineField({
      name: "howItWorksTitle",
      title: "Title",
      type: "string",
      group: "howItWorks",
    }),
    defineField({
      name: "howItWorksSteps",
      title: "Steps",
      type: "array",
      of: [{ type: "step" }],
      group: "howItWorks",
      validation: (r) => r.max(6),
    }),
    defineField({
      name: "operatorsEyebrow",
      title: "Eyebrow",
      type: "string",
      group: "operators",
    }),
    defineField({
      name: "operatorsTitle",
      title: "Title",
      type: "string",
      group: "operators",
    }),
    defineField({
      name: "operatorsDescription",
      title: "Description",
      type: "text",
      rows: 4,
      group: "operators",
    }),
    defineField({
      name: "operatorBenefits",
      title: "Benefits",
      type: "array",
      of: [{ type: "benefit" }],
      group: "operators",
      validation: (r) => r.max(6),
    }),
    defineField({
      name: "operatorsCtaLabel",
      title: "CTA button label",
      type: "string",
      group: "operators",
    }),
    defineField({
      name: "operatorsCtaHref",
      title: "CTA link (mailto: or URL)",
      type: "string",
      group: "operators",
    }),
    defineField({
      name: "valueProps",
      title: "Value props",
      description: "Short bullet points shown above the bottom CTA",
      type: "array",
      of: [{ type: "string" }],
      group: "cta",
    }),
    defineField({
      name: "ctaTitle",
      title: "Title",
      type: "string",
      group: "cta",
    }),
    defineField({
      name: "ctaDescription",
      title: "Description",
      type: "text",
      rows: 3,
      group: "cta",
    }),
    defineField({
      name: "ctaPrimaryLabel",
      title: "Primary button label",
      type: "string",
      group: "cta",
    }),
    defineField({
      name: "ctaSecondaryLabel",
      title: "Secondary button label",
      type: "string",
      group: "cta",
    }),
  ],
  preview: {
    prepare() {
      return { title: "Homepage" };
    },
  },
});
