import { defineField, defineType } from "sanity";

export const tour = defineType({
  name: "tour",
  title: "Tour",
  type: "document",
  groups: [
    { name: "listing", title: "Listing", default: true },
    { name: "details", title: "Details" },
    { name: "operator", title: "Operator" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "listing",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "listing",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "featured",
      title: "Featured on homepage",
      type: "boolean",
      group: "listing",
      initialValue: false,
    }),
    defineField({
      name: "description",
      title: "Short description",
      type: "text",
      rows: 3,
      group: "listing",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "destination",
      title: "Destination",
      type: "string",
      group: "listing",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "state",
      title: "State / territory",
      type: "string",
      group: "listing",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "duration",
      title: "Duration",
      type: "string",
      group: "listing",
      description: 'e.g. "8 hours"',
    }),
    defineField({
      name: "priceAud",
      title: "Price (AUD)",
      type: "number",
      group: "listing",
      validation: (r) => r.required().min(0),
    }),
    defineField({
      name: "image",
      title: "Image",
      type: "image",
      group: "listing",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alt text",
          type: "string",
          description: "Describe the image for accessibility and SEO.",
        }),
      ],
      validation: (r) => r.required(),
    }),
    defineField({
      name: "rating",
      title: "Rating",
      type: "number",
      group: "listing",
      validation: (r) => r.min(0).max(5),
      initialValue: 4.5,
    }),
    defineField({
      name: "reviewCount",
      title: "Review count",
      type: "number",
      group: "listing",
      initialValue: 0,
      validation: (r) => r.min(0),
    }),
    defineField({
      name: "longDescription",
      title: "Long description",
      type: "text",
      rows: 8,
      group: "details",
    }),
    defineField({
      name: "highlights",
      title: "Highlights",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "includes",
      title: "What's included",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "meetingPoint",
      title: "Meeting point",
      type: "string",
      group: "details",
    }),
    defineField({
      name: "maxGuests",
      title: "Max guests",
      type: "number",
      group: "details",
      initialValue: 20,
      validation: (r) => r.min(1),
    }),
    defineField({
      name: "commissionRate",
      title: "Commission rate",
      type: "number",
      group: "operator",
      description: "Decimal, e.g. 0.15 for 15%",
      initialValue: 0.15,
      validation: (r) => r.min(0).max(1),
    }),
    defineField({
      name: "operatorName",
      title: "Operator name",
      type: "string",
      group: "operator",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "operatorLocation",
      title: "Operator location",
      type: "string",
      group: "operator",
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "destination",
      media: "image",
    },
    prepare({ title, subtitle }) {
      return { title, subtitle };
    },
  },
  orderings: [
    {
      title: "Title A–Z",
      name: "titleAsc",
      by: [{ field: "title", direction: "asc" }],
    },
    {
      title: "Featured first",
      name: "featuredDesc",
      by: [
        { field: "featured", direction: "desc" },
        { field: "title", direction: "asc" },
      ],
    },
  ],
});
